# Starting with a comment
events { # inline event comment
    worker_connections # standard directive split
    1024; # value comment
} # closing events
http {
    # Nested comment here
    server {
        listen 80; #listen port
        server_name #split name
        example.com;
        location / { # opening location
            # absolute whitespace and comments
            root /data; # root dir
        } # close location
    } # close server
} # close http