events { worker_connections 1024; }
http {
    server {
        listen 80;
        char_set "utf-8";
        # Is this a comment? ; { } 
        add_header X-String "this # is not a comment; and this } is not a closing brace";
        return 200 'more # fake comments; {';
    }
}