events {}
http {
    server {
        listen 80;
        location / {
            location /a {
                location /b {
                    location /c {
                        location /d {
                            location /e {
                                location /f {
                                    return 200 "Deep!";
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}