# Starting with a comment
server { # opening server
    listen 80; #listen port
    server_name #split name
    example.com;
    location / { # opening location
        # absolute whitespace and comments
        root /data; # root dir
    } # close location
} # close server
