server {
    listen 127.0.0.1:8080;
    server_name example.com www.example.com;
    client_max_body_size 10m;
    error_page 404 500 /error.html;

    location / {
        alias /var/www/html;
        index index.html index.htm;
    }

    location /uploads {
        alias /var/www/uploads;
        client_max_body_size 25m;

        if /uploads {
            return 403 Forbidden;
        }
    }

    location /old {
        return 301 /new;
    }
}
