server {
    listen 127.0.0.1:8080;
    listen 127.0.0.1:8081;
    listen 8082;
    server_name multilisten.local;
    root /var/www/multilisten;
    index index.html;

    location / {
        alias /var/www/multilisten;
        index index.html;
    }
}
