server {
    listen 80;
    server_name site-one.local;

    location / {
        alias /var/www/site-one;
        index index.html;
    }
}

server {
    listen 8081;
    server_name site-two.local admin.site-two.local;
    error_page 404 /404.html;

    location / {
        alias /var/www/site-two;
        index index.htm;
    }

    location /api {
        client_max_body_size 5m;
        return 200 "api root";
    }
}
