server {
    listen 80;
    location / {
        if /a {
            return 200 "a";
        }
    }
    location /a {
        if /b {
            return 200 "b";
        }
    }
    location /b {
        if /c {
            return 200 "c";
        }
    }
    location /c {
        if /d {
            return 200 "d";
        }
    }
}
