server {
    listen 0.0.0.0:8080;
    root html;

    location / {
        index index.html;
    }
    location /example {
        return 301 https://www.example.com;
    }
    location /test {
        return 302 /;
    }
    location /html {
        return 302 /alt_index.html;
    }
}