server {
    listen 0.0.0.0:8080;
    server_name localhost;
    root html;

    location / {
        limit_except GET;
        index index.html;
    }

    location /uploads {
        alias html;
        limit_except GET;
        index upload_del.html;
    }

    location /upload_storage {
        limit_except GET POST DELETE;
        upload_store html/upload_storage;
        autoindex on;
    }
}